### ISSUE TITLE
X-Bogus

### ISSUE THREAD

**Issue by luckmc** [xishandong/crawlProject#10]
用这个是否可以解决，我不会利用,UP可以看一下：

https://github.com/B1gM8c/X-Bogus

**Comment by xishandong** [comment]
应该是可以的，你只需要在ajax_requests函数将x-b加到params里面，注意生成x-b的时候，url需要传完整的xxx?a=qqq&b=sss这样的

**Comment by xishandong** [comment]
他写的这个是失效了的，douyin应该更新了签名

**Comment by luckmc** [comment]
那看下这个。刚找的。目前可以用。他就调用了这个[X-Bogus](https://github.com/B1gM8c/X-Bogus)
https://github.com/PearNoDec/DouYinParse
他是远程调用的。能改成本地就好了

**Comment by xishandong** [comment]
我看README里面的xb是基于之前那个失效的服务

**Comment by xishandong** [comment]
改好了，你去下载可用的x-b签名算法既可，第一个仓库里的好像是可以的，代码我上传了

**Comment by luckmc** [comment]
感谢UP更新分享！

**Comment by xishandong** [comment]
没有呀 是不是你cookie的问题？我今天跑了一天都可以的

**Comment by xishandong** [comment]
检查检查cookie，还有其他信息，我今天是可以跑通的发自我的 iPhone在 2023年9月25日，17:58，天使 ***@***.***> 写道：﻿

改好了，你去下载可用的x-b签名算法既可，第一个仓库里的好像是可以的，代码我上传了

我更新到最新版本后运行时还是失败了，是因为X-Bogus又换新的算法了吗？

**Comment by luckmc** [comment]
没问题啊。我这边运行正常哈，UP主辛苦了！
我用的还是前几天更新的代码。

**Comment by wwfcnu** [comment]
douyin 是更新了x-b的验证算法吗

**Comment by xishandong** [comment]
晚上我回去看看发自我的 iPhone在 2023年10月18日，14:19，wwfcnu ***@***.***> 写道：﻿
douyin 是更新了x-b的验证算法吗

**Comment by wwfcnu** [comment]
> 晚上我回去看看发自我的 iPhone在 2023年10月18日，14:19，wwfcnu ***@***.***> 写道：﻿ douyin 是更新了x-b的验证算法吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

搞错了，还能用
