### ISSUE TITLE
抖音全站代码更新

### ISSUE THREAD

**Issue by luckmc** [xishandong/crawlProject#11]
UP大大，吃顿饭的功夫，同样的代码。
现在不能用了，运行提示：
'str' object has no attribute 'domain' retry_times:1:5...
'str' object has no attribute 'domain' retry_times:2:5...

您那边看看，验证一下，打扰了

**Comment by xishandong** [comment]
我的没问题呀 你重新拉最新的试一试

**Comment by luckmc** [comment]
我拉取的是这个：
https://github.com/xishandong/crawlProject/tree/main/%E8%BF%9B%E9%98%B6%E7%AF%87/%E5%9F%BA%E7%A1%80%E7%BB%BC%E5%90%88/douyin%E5%85%A8%E7%AB%99%E7%88%AC%E5%8F%96
使用的pycharm，关键昨天我成功运行了。然后吃个饭回来，就这样了：
'str' object has no attribute 'domain' retry_times:1:5...
如果您那边没问题。我再尝试下，是不是我的环境出问题了。

**Comment by xishandong** [comment]
你去拉最新的 这个错估计不是代码的问题 domain是cookie或者发请求需要的 不知道为什么变成了str类型

**Comment by luckmc** [comment]
我就是拉的最新的代码。什么都没改。只添加了cookie，我是这么加的，麻烦帮我看下，是不是我cookie的问题

self.cookies = {'ttwid=1%7CZx3pZiC6yA3JhfPFS_dNnx8xGBmU9xcQgkxh4Y1ASeE%7C1683423749%7Cb3ca9957bf102f1915a8ad7c4a801a7291b039b3158ed1874d92adec8422c03c; douyin.com; csrf_session_id=c88c59097b1c42d9796da415a7bd8c4a; d_ticket=450d86c4012f9e3ae88674a5bd2ca830347fc; store-region-src=uid; store-region=cn-ha; xgplayer_user_id=481536357302; device_web_cpu_core=8; device_web_memory_size=8; webcast_local_quality=null; __security_server_data_status=1; my_rd=1; b-user-id=4fb459bb-3140-bbc1-aaaf-0a5f5858e628; s_v_web_id=verify_lm623eni_hXh4UhH7_OT15_4rj1_9t1F_MAVmkrhgPVVl; passport_csrf_token=1be39e6c7d0dc9b1fbb55317106607bb; passport_csrf_token_default=1be39e6c7d0dc9b1fbb55317106607bb; architecture=amd64; __live_version__=%221.1.1.4094%22; webcast_local_quality=origin; webcast_leading_last_show_time=1694692888348; webcast_leading_total_show_times=7; download_guide=%223%2F20230912%2F1%22; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCSXI1REgxT25aRjcyK1oyTlZqSlA0QWwwdlhJUmo5Tk9mVHFvWlFFSzd1bFU4OTFQOTBYd0VKTW01bmdOeXFPdEMvQ3pqR1ZlTi8reUcvVHFTMkRjYmc9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ==; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%2C%22isForcePopClose%22%3A1%7D; _bd_ticket_crypt_doamin=3; pwa2=%220%7C0%7C3%7C0%22; strategyABtestKey=%221695439105.37%22; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Afalse%2C%22volume%22%3A0.169%7D; SEARCH_RESULT_LIST_TYPE=%22single%22; n_mh=46Q2Z7yJMf0y-eclCru5N7I90XBmTRa_Sy2_NGKbTZc; sso_uid_tt=1bcca1951615c54c5d30467e5abab4ca; sso_uid_tt_ss=1bcca1951615c54c5d30467e5abab4ca; toutiao_sso_user=6c176b44499b7746f3e6d612ba70b1cc; toutiao_sso_user_ss=6c176b44499b7746f3e6d612ba70b1cc; passport_assist_user=Cjw4UfTG5znBkWufT3Rdh7QtkJlnR6QuIYp200-bl6U2quul8UIOtXI9cZ7OLUo28Ts_1a6N06vaNoyaDbEaSgo8zdfW3UF15jlbvPHm5RH3oa1Aa1_FtPQxW-XA4u3OYU1Ipi-avRtBVhXeeHF5G06q7vMyvk2_QHbl5jzGEJbYvA0Yia_WVCABIgEDz_iswQ%3D%3D; sid_ucp_sso_v1=1.0.0-KDkzOWVjNmNlMGMzM2U4MjFiZDM1MzRhYzE1ZTZiMWJlYjJiMWNhNmIKHQizuqj7ugIQrsy5qAYY7zEgDDCu-sLSBTgGQPQHGgJsZiIgNmMxNzZiNDQ0OTliNzc0NmYzZTZkNjEyYmE3MGIxY2M; ssid_ucp_sso_v1=1.0.0-KDkzOWVjNmNlMGMzM2U4MjFiZDM1MzRhYzE1ZTZiMWJlYjJiMWNhNmIKHQizuqj7ugIQrsy5qAYY7zEgDDCu-sLSBTgGQPQHGgJsZiIgNmMxNzZiNDQ0OTliNzc0NmYzZTZkNjEyYmE3MGIxY2M; odin_tt=eff8f7f6017f964300376971559330e6ec33d79b173907480a5487836d72d4424dc67b72019ad2b96b8b3a12d29835ca; passport_auth_status=5ebb504480f632fa96fcc992f63bf392%2C70d6045c3e44882cdfee133be7ca6113; passport_auth_status_ss=5ebb504480f632fa96fcc992f63bf392%2C70d6045c3e44882cdfee133be7ca6113; uid_tt=d0e0f9776e2b025bced92d2ccfe0b952; uid_tt_ss=d0e0f9776e2b025bced92d2ccfe0b952; sid_tt=585fa50b2957def5b8679dda6e5afbc7; sessionid=585fa50b2957def5b8679dda6e5afbc7; sessionid_ss=585fa50b2957def5b8679dda6e5afbc7; _bd_ticket_crypt_cookie=49e26cb11f0ccb62af5e7d183d091935; LOGIN_STATUS=1; sid_guard=585fa50b2957def5b8679dda6e5afbc7%7C1695442487%7C5183994%7CWed%2C+22-Nov-2023+04%3A14%3A41+GMT; sid_ucp_v1=1.0.0-KGQzZGU5ZDg5ZmZlYzYxM2VkNzY3MGRhNDQwYWQ5ZWZjMjE0NDNjMTEKGQizuqj7ugIQt8y5qAYY7zEgDDgGQPQHSAQaAmhsIiA1ODVmYTUwYjI5NTdkZWY1Yjg2NzlkZGE2ZTVhZmJjNw; ssid_ucp_v1=1.0.0-KGQzZGU5ZDg5ZmZlYzYxM2VkNzY3MGRhNDQwYWQ5ZWZjMjE0NDNjMTEKGQizuqj7ugIQt8y5qAYY7zEgDDgGQPQHSAQaAmhsIiA1ODVmYTUwYjI5NTdkZWY1Yjg2NzlkZGE2ZTVhZmJjNw; live_push_record=%7B%22roomId%22%3A%227281615315681758012%22%2C%22startTime%22%3A1695434400%2C%22endTime%22%3A1695448800%7D; publish_badge_show_info=%221%2C0%2C0%2C1695442519435%22; __ac_nonce=0650e8ed7007a00fffbe9; __ac_signature=_02B4Z6wo00f01n2LcFgAAIDDHoGwMs3efZ59q3TAAPp7h9IDrfIPTzd55tfGhl6NgPoP.xp6n7rgZuhqT0Itmw4mHwCoFZkF-ocbgM.f1.NhE1tP9BYdUWvEMYM4aw3yd.FJdV20uUZuORb.fd; FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAAp0q9r1LspS70JWKwvXUZn-qq1icmlcCabTf61uKHY2o%2F1695484800000%2F0%2F0%2F1695453498060%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAAp0q9r1LspS70JWKwvXUZn-qq1icmlcCabTf61uKHY2o%2F1695484800000%2F0%2F1695452898061%2F0%22; VIDEO_FILTER_MEMO_SELECT=%7B%22expireTime%22%3A1696057698091%2C%22type%22%3A1%7D; tt_scid=kZkUuRNJJM12JV7cptK9RexgqxmrtsZrLVy-mN4bdvmY6RUkQXi8.izhDYaFRefC372d; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A2560%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A8%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A100%7D%22; IsDouyinActive=true; home_can_add_dy_2_desktop=%221%22; msToken=uSSY5rjHyvbkxvvNr2_gzDbdG6poJGMmxz6E8h1R7gxkvDyxjea8GioddwYq_sqWKzrk5jqt9VblC8I9Mo6A0V45ZWlc-HkTYg2X5LJS71Hc3Dd6RKhDmQ==; passport_fe_beating_status=true; msToken=QoBz0kHoeQD99UiiFQTdyWs_rdEL5PvK6OVJ9wOVnJghnS3I17g8wRTqm49yG80sVThmd8fTj64Y8fKf30pyLALp3Kjqv7aRV83e-UUTxT7BEvVy0mbyzRO3tbMx0cw='}

**Comment by xishandong** [comment]
对的，你的cookie有问题，cookie是要以键值对的形式才可以
