### ISSUE TITLE
小红书的问题

### ISSUE THREAD

**Issue by pztpzsapp** [xishandong/crawlProject#15]
# 如图所示：
![图片](https://github.com/xishandong/crawlProject/assets/152942313/14bcfcd8-cb17-4949-8f76-739301b34182)

## 请问作者大大：这是什么原因导致的？我该如何解决

**Comment by pztpzsapp** [comment]
## 补充：这是jssss.js里面的内容
![图片](https://github.com/xishandong/crawlProject/assets/152942313/cdf9fc62-9ece-4733-b761-c906a88b8136)

**Comment by xishandong** [comment]
你xhs算法都没放进去肯定没有呀

**Comment by pztpzsapp** [comment]
> 你xhs算法都没放进去肯定没有呀

xh算法s可以commit到girhub上吗。我找不到

**Comment by xishandong** [comment]
放进去了我不得被某书发律师函了😀发自我的 iPhone在 2023年12月11日，10:25，pztpzsapp ***@***.***> 写道：﻿

你xhs算法都没放进去肯定没有呀

xh算法s可以commit到girhub上吗。我找不到

**Comment by pztpzsapp** [comment]
> 放进去了我不得被某书发律师函了😀发自我的 iPhone在 2023年12月11日，10:25，pztpzsapp ***@***.***> 写道：﻿ 你xhs算法都没放进去肯定没有呀 xh算法s可以commit到girhub上吗。我找不到 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

can i add u qq？
