### ISSUE TITLE
npm的install打错了，另外请问有讨论群吗

### ISSUE THREAD

**Issue by evilCYH** [xishandong/crawlProject#16]
install打成insatll了：
npm insatll jsdom # js模拟浏览器的dom和bom
npm insatll tough-cookie # 浏览器cookie

另外看见之前issue有说建讨论群，请问现在有吗

**Comment by silivers** [comment]
我也想说这个问题

**Comment by xishandong** [comment]
好的，我现在修改，讨论群目前还没有建，主要我开始搬砖了，苦于生活劳累
