### ISSUE TITLE
建议把等级改成按蜘蛛等级划分，最高级为蜘蛛精

### ISSUE THREAD

**Issue by anzhi0708** [xishandong/crawlProject#17]
以下是按蜘蛛等级划分的列表，最高级为蜘蛛精：

| 等级       | 标识  | 难度描述       |
|----------|-----|------------|
| 蜘蛛卵       | 0   | 入门          |
| 幼蛛         | 00  | 踏过门槛了       |
| 小蜘蛛       | *   | 初级          |
| 大蜘蛛       | **  | 比初级高一点     |
| 巨蜘蛛       | *** | 中等难度       |
| 辉耀蜘蛛     | +   | 中上难度       |
| 毒蛛         | ++  | 比较难         |
| 蜘蛛王       | +++ | 难           |
| 蜘蛛精       | KING| 地狱          |

这样一来，每个等级都对应一种蜘蛛，最高级别则是蜘蛛精。

**Comment by xishandong** [comment]
哈哈哈也可以
