### ISSUE TITLE
js环境检测-小红书-get方法好像失效

### ISSUE THREAD

**Issue by submato** [xishandong/crawlProject#4]
如题，js环境检测-小红书-get方法好像失效，求一份详细的运行文档，如：jssss.js 文件中的cookie是干嘛用的

**Comment by submato** [comment]
试过/api/sns/web/v2/comment/page 这个api

**Comment by xishandong** [comment]
cookie参与生成x-s

**Comment by xishandong** [comment]
我这里运行没有问题 应该是你没传对cookie和localstorage

**Comment by submato** [comment]
cookie已经配置了，localstorage没配置，有什么影响吗，localstorage应该配置什么 能够举两个例子吗



---原始邮件---
发件人: "xishan ***@***.***&gt;
发送时间: 2023年8月16日(周三) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xishandong/crawlProject] js环境检测-小红书-get方法好像失效 (Issue #4)




 
我这里运行没有问题 应该是你没传对cookie和localstorage

**Comment by xishandong** [comment]
可以补充一下浏览器的知识 这些都是浏览器的对象
