### ISSUE TITLE
求一份简单的how to run

### ISSUE THREAD

**Issue by submato** [xishandong/crawlProject#6]
如题，自己尝试了许久，没跑起来，求一份how to run 文档

**Comment by xishandong** [comment]
哪个项目

**Comment by submato** [comment]
小红书



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 凌晨0:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6)




 
哪个项目

**Comment by xishandong** [comment]
小红书需要把cookie和localstorage放进去就可以了

**Comment by xishandong** [comment]
格式也在js文件中写好了，但是注意cookie是发送请求的cookie 不是document里面的

**Comment by submato** [comment]
是的，我是按照这样做的，但是好像不行。 评论接口返回406，我明天再试一下。 愿意付费咨询



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 凌晨0:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6)




 
格式也在js文件中写好了，但是注意cookie是发送请求的cookie 不是document里面的

**Comment by xishandong** [comment]
是只有评论接口还是所有接口？我记得我今天下午也爬过是没有问题的发自我的 iPhone在 2023年9月1日，00:35，subtropical-tomato ***@***.***> 写道：﻿
是的，我是按照这样做的，但是好像不行。 评论接口返回406，我明天再试一下。 愿意付费咨询







---原始邮件---

发件人: ***@***.***&gt;

发送时间: 2023年9月1日(周五) 凌晨0:32

收件人: ***@***.***&gt;;

抄送: ***@***.******@***.***&gt;;

主题: Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6)









 

格式也在js文件中写好了，但是注意cookie是发送请求的cookie 不是document里面的

**Comment by submato** [comment]
好的，我明天再试一下。&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 凌晨0:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6)




 是只有评论接口还是所有接口？我记得我今天下午也爬过是没有问题的发自我的 iPhone在 2023年9月1日，00:35，subtropical-tomato ***@***.***&gt; 写道：﻿ 
 是的，我是按照这样做的，但是好像不行。 评论接口返回406，我明天再试一下。 愿意付费咨询 
 
 
 
 
 
 
 
 ---原始邮件--- 
 
 发件人: ***@***.***&amp;gt; 
 
 发送时间: 2023年9月1日(周五) 凌晨0:32 
 
 收件人: ***@***.***&amp;gt;; 
 
 抄送: ***@***.******@***.***&amp;gt;; 
 
 主题: Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6) 
 
 
 
 
 
 
 
 
 
   
 
 格式也在js文件中写好了，但是注意cookie是发送请求的cookie 不是document里面的

**Comment by submato** [comment]
still doesn't work
<img width="1205" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/0e34e270-57c7-4a13-905d-f8381856e1db">
<img width="929" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/f712f22a-472c-41bc-be03-8aa3d6b78b14">

**Comment by xishandong** [comment]
错了，cookie格式错了
![image](https://github.com/xishandong/crawlProject/assets/100206449/1a94a379-b07d-4046-91e9-c9d4dccec510)
我都把这个标注的这么明显了。。。

**Comment by xishandong** [comment]
明显那是一个数组嘛，如果但一个字符串我搞一个数组干嘛

**Comment by submato** [comment]
你这个给的是dict类型啊。。


数组也没用啊，会报错






                       
Original
                       
                     

From:"DongXishan"< ***@***.*** &gt;;

Date:2023/9/1 17:16

To:"xishandong/crawlProject"< ***@***.*** &gt;;

CC:"subtropical-tomato"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [xishandong/crawlProject] 求一份简单的how to run (Issue #6)




 
错了，cookie格式错了
 
 我都把这个标注的这么明显了。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
a

**Comment by submato** [comment]
你这个给的是dict类型啊。。
<img width="972" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/2a980744-04ce-4856-87c1-d61aef3e10de">


数组也没用啊，会报错
<img width="893" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/22f909a3-8507-457d-9c5a-d98fc26516e0">

**Comment by submato** [comment]
你这个给的是dict类型啊。。
<img width="972" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/2a980744-04ce-4856-87c1-d61aef3e10de">


数组也没用啊，会报错
<img width="893" alt="image" src="https://github.com/xishandong/crawlProject/assets/55040284/22f909a3-8507-457d-9c5a-d98fc26516e0">

**Comment by xishandong** [comment]
不是啊 在js里面…..

**Comment by xishandong** [comment]
你的图二….数组和对象还是区别蛮大的嘛

**Comment by xishandong** [comment]
以等号和逗号分隔的cookie，我还给了案例样式应该怎么贴的
