### ISSUE TITLE
douyin全站爬取接口是否失效

### ISSUE THREAD

**Issue by luckmc** [xishandong/crawlProject#8]
老哥抽时间看下哈，我更换cookies还一直在重试，不能获取内容

支持你的视频，多一句嘴，如果B站不让发可以去油管开一个频道啊！

**Comment by xishandong** [comment]
哪个接口？我今天才看了没问题呀

**Comment by luckmc** [comment]
获取用户主页视频链接。您那边运行没问题？可以获取到？我这边运行一直在重试5次。换了cookies也一样

**Comment by luckmc** [comment]
是否我获取到的cookies不对。我是登录到网页版，在用户主页获取的cookies，之前运行没问题。今天发现获取不到内容了，所以更换了cookies还是不行。以为接口失效了。

**Comment by xishandong** [comment]
我看了，要加x-b才可以了，这个接口也开始检测了

**Comment by luckmc** [comment]
是这个吗？https://github.com/luckmc/X-Bogus
我自己不会利用，可否集成到up的代码里？

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年9月22日 10:13
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [xishandong/crawlProject] douyin全站爬取接口是否失效 (Issue #8)


我看了，要加x-b才可以了，这个接口也开始检测了

―
