### ISSUE TITLE
如何下载抖音某一用户下发布的所有视频

### ISSUE THREAD

**Issue by wwfcnu** [xishandong/crawlProject#9]

**Comment by xishandong** [comment]
需要加x-b才可以获取用户所有内容了

**Comment by xishandong** [comment]
有了x-b之后
items = dou.get_user_post('MS4wLjABAAAA0fiq261i6th1gRCsGrZ6SRxCT9DdEz3aJ5nBRnR14N0')
    for item in items:
        dou.download(item)
用这个方法即可下载，根据你的喜好也可以改为多线程下载
